### ISSUE TITLE
Modular reduction/bit-shifting?

### ISSUE THREAD

**Issue by jon-chuang** [nucypher/nufhe#20]
Can TFHE implement modular reduction efficiently?

**Comment by fjarri** [comment]
I am not sure I understand what you have in mind - TFHE and nuFHE operate on single encrypted bits. Could you elaborate?

**Comment by jon-chuang** [comment]
Hi, I think I made a mistake, TFHE is not really what I want, in particular, even accelerated on a GPU, composing a bit-level circuit is immensely costly to emulate what I need.
