### ISSUE TITLE
fatal error: include/cufhe_cpu.h: No such file or directory

### ISSUE THREAD

**Issue by bpradeep508** [nucypher/nufhe#22]
(base) user@HP-Z8-G4-Workstation:~/cuFHE-master/cufhe/test$ cc test_api_cpu.cc
test_api_cpu.cc:24:10: fatal error: include/cufhe_cpu.h: No such file or directory
 #include <include/cufhe_cpu.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by fjarri** [comment]
Seems like that should be an issue for [this project](https://github.com/vernamlab/cuFHE)?

**Comment by bpradeep508** [comment]
Kindly elaborate in detail

**Comment by fjarri** [comment]
This is a Python project, it doesn't contain any C/C++ files. So, whatever you are trying to compile is not a part of it. Based on the folder name I assumed that these files are a part of cuFHE, which I linked above.

**Comment by bpradeep508** [comment]
same error while running of cuda

(base) user@HP-Z8-G4-Workstation:~/cuFHE-master/cufhe/test$ nvcc
test_api_gpu.cutest_api_gpu.cu:24:10: fatal error: include/cufhe_gpu.cuh:
No such file or directory
 #include <include/cufhe_gpu.cuh>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated

**Comment by bpradeep508** [comment]
(base) user@HP-Z8-G4-Workstation:~/cuFHE-master/cufhe/python$ python
test_circuits_gpu.py
  File "test_circuits_gpu.py", line 41
    print "Encrypted message : ", msg
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean
print("Encrypted message : ", msg)?

**Comment by fjarri** [comment]
Once again, what you are trying to compile/run is a part of `cuFHE`. This project is `nuFHE`. Two different projects. Please open an issue for [`cuFHE`](https://github.com/vernamlab/cuFHE)

**Comment by bpradeep508** [comment]
(base) user@HP-Z8-G4-Workstation:~/cuFHE-master/cufhe/python$ python
test_gpu.py
Traceback (most recent call last):
  File "test_gpu.py", line 30, in <module>
    import lib.fhepy_gpu as fhe
ModuleNotFoundError: No module named 'lib.fhepy_gpu'

**Comment by bpradeep508** [comment]
installation is completed successfully. when i am executing test programs
using python and c++ both showing errors
