### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by rcannon** [nucypher/nufhe#27]
I am unable to find the script used to evaluate the performance of NuFHE as stated in the README. I have tried 
`pytest -rA test/test_gates.py`
but none of the results seem to match the reported statistic. I understand the result will likely be different numerically, but I can't find the statistic that matches in name.

**Comment by fjarri** [comment]
The speed measurement is a little barebones. Run `pytest -v -s test/test_gates.py` - the performance info is just `print` statements in the tests (sorry about that). Add `-m perf` for only performance tests, and `--heavy-performance-load` if you got a good GPU (which is recommended if you want to replicate the results from Readme).

**Comment by rcannon** [comment]
Thanks!
