### ISSUE TITLE
Connect TFHE to other HE schemes

### ISSUE THREAD

**Issue by lucacolombo97** [nucypher/nufhe#37]
Hi all! 
I'd like to know if it is possible to connect TFHE with another HE scheme working on integers like BGV/BFV in order to perform SIMD operations by using functions on Lwe already provided by this library.

Thanks in advance.

**Comment by fjarri** [comment]
Sorry for a delayed response. There is a thing called [CHIMERA](https://eprint.iacr.org/2018/758). 

This project is probably not going to implement it, it is frozen, but there is a new iteration of an FHE software in development in a branch of NuCypher, which hopefully will be announced soon.

**Comment by lucacolombo97** [comment]
Thank you very much for your response.
